models/Mantenimientos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "mantenimientos".
 *
 * @property int $id
 * @property int $idMaquinas
 * @property string|null $descripcion
 * @property int $estado
 * @property string $fecha
 *
 * @property Maquinas $idMaquinas0
 */
class Mantenimientos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mantenimientos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idMaquinas', 'fecha'], 'required'],
            [['idMaquinas', 'estado'], 'integer'],
            [['descripcion'], 'string', 'max' => 255],
            [['fecha'], 'safe'],
            [['idMaquinas'], 'exist', 'skipOnError' => true, 'targetClass' => Maquinas::class, 'targetAttribute' => ['idMaquinas' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idMaquinas' => 'Máquina',
            'descripcion' => 'Descripción',
            'estado' => 'Estado',
            'fecha' => 'Fecha programada',
        ];
    }

    /**
     * Gets query for [[IdMaquinas0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdMaquinas0()
    {
        return $this->hasOne(Maquinas::class, ['id' => 'idMaquinas']);
    }
    
public function beforeSave($insert)
{
    if (parent::beforeSave($insert)) {
        // Verifica si el estado ha sido modificado manualmente
        if (!$this->isAttributeChanged('estado')) {
            // Solo actualiza el estado basado en la fecha si no ha sido modificado manualmente
            if (strtotime($this->fecha) <= strtotime(date('Y-m-d'))) {
                $this->estado = 0; // Completado
            }
        }
        return true;
    }
    return false;
}

}

controllers/MantenimientosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Mantenimientos;
use app\models\search\MantenimientosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MantenimientosController implements the CRUD actions for Mantenimientos model.
 */
class MantenimientosController extends Controller
{
    public function actionUpdateEstado()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON; // Asegúrate de que la respuesta es JSON

        if (Yii::$app->request->isPost) {
            $id = Yii::$app->request->post('id');
            $estado = Yii::$app->request->post('estado');

            $model = Mantenimientos::findOne($id);
            if ($model) {
                $model->estado = (int)$estado; // Convertir el estado a entero
                if ($model->save()) {
                    return ['success' => true];
                } else {
                    return ['success' => false, 'error' => $model->getErrors()];
                }
            }
        }

        return ['success' => false, 'error' => 'Invalid request'];
    }

    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Mantenimientos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new MantenimientosSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Mantenimientos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Mantenimientos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Mantenimientos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Mantenimientos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
public function actionUpdate($id)
{
    $model = $this->findModel($id);

    if ($this->request->isPost) {
        $estadoAnterior = $model->estado; // Guarda el estado anterior

        if ($model->load($this->request->post())) {
            // Si el estado se ha cambiado manualmente, respetar ese cambio
            if ($model->isAttributeChanged('estado')) {
                // Evita que beforeSave modifique el estado si ya fue cambiado manualmente
                $model->estado = (int)$model->estado;
            } else {
                // Mantén el estado anterior si no fue cambiado
                $model->estado = $estadoAnterior;
            }

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
    }

    return $this->render('update', [
        'model' => $model,
    ]);
}


    /**
     * Deletes an existing Mantenimientos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Mantenimientos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Mantenimientos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Mantenimientos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/mantenimientos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var yii\widgets\ActiveForm $form */
/** @var app\models\Productos[] $productos */

?>

<div class="mantenimientos-form card shadow-sm p-4">

    <?php $form = ActiveForm::begin(['options' => ['class' => 'form-horizontal']]); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'idMaquinas')->label('Máquina*')->dropDownList(
                ArrayHelper::map(\app\models\Maquinas::find()->all(), 'id', function($maquina) {
                    return $maquina->nombre . ' - ' . $maquina->numero_de_serie;
                }), 
                ['prompt' => 'Seleccione una Máquina']
            ) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'descripcion')->label('Descripción')->textarea(['maxlength' => true, 'rows' => 1, 'placeholder' => 'Ej: Mantenimiento preventivo del dispensador de monedas']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'fecha')->label('Fecha*')->input('date') ?>
        </div>
    </div>

    <div class="form-group text-right">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<style>
    .mantenimientos-form .form-group {
        margin-bottom: 1rem;
    }
    .mantenimientos-form .form-control {
        border-radius: 0.25rem;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .help-block {
    color: red;
    padding-left: 3px;
}

</style>

views/mantenimientos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\search\MantenimientosSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="mantenimientos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'idMaquinas') ?>

    <?= $form->field($model, 'descripcion') ?>

    <?= $form->field($model, 'estado') ?>

    <?= $form->field($model, 'fecha') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/mantenimientos/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var app\models\Productos[] $productos */

$this->title = 'Nuevo Mantenimiento';

?>
<div class="mantenimientos-create container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .mantenimientos-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .mantenimientos-create {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
</style>

views/mantenimientos/index.php
<?php

use app\models\Mantenimientos;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

/** @var yii\web\View $this */
/** @var app\models\search\MantenimientosSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Mantenimientos';

?>
<div class="mantenimientos-index container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Nuevo Mantenimiento', ['create'], ['class' => 'btn btn-primary']) ?>
    </div>
    <div class="input-group mb-3" style="width: 450px;">
        <input type="text" id="mantenimientos-search" class="form-control table-search" placeholder="Buscar...">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary btn-reset-search" type="button" id="reset-search">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>

    <div class="card shadow-sm p-4">
        <?php Pjax::begin(); ?>
        <div class="card-body p-0">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => ['class' => 'table table-hover mb-0', 'id' => 'mantenimientos-table'],
                'rowOptions' => function($model) {
                    return $model->estado ? ['class' => 'estado-completado'] : ['class' => 'estado-pendiente'];
                },
                'columns' => [
                    [
                        'attribute' => 'idMaquinas',
                        'value' => 'idMaquinas0.nombre',
                        'label' => 'Máquina'
                    ],
                    [
                        'attribute' => 'idMaquinas',
                        'value' => 'idMaquinas0.numero_de_serie',
                        'label' => 'Número de Serie'
                    ],
                    [
                        'attribute' => 'descripcion',
                        'format' => 'ntext',
                        'value' => function ($model) {
                            return !empty($model->descripcion) ? $model->descripcion : '-';
                        }
                    ],
                    [
                        'attribute' => 'estado',
                        'format' => 'raw',
                        'value' => function ($model) {
                            $checked = $model->estado ? 'checked' : '';
                            $id = 'estado-' . $model->id;
                            return Html::checkbox('estado', $model->estado, [
                                'id' => $id,
                                'class' => 'estado-checkbox',
                                'data-id' => $model->id,
                            ]);
                        },
                        'label' => 'Estado'
                    ],
                    [
                        'attribute' => 'fecha',
                        'format' => ['date', 'php:d-m-Y'],
                    ],
                    [
                        'class' => ActionColumn::class,
                        'urlCreator' => function ($action, Mantenimientos $model, $key, $index, $column) {
                            return Url::toRoute([$action, 'id' => $model->id]);
                        },
                        'contentOptions' => ['class' => 'text-right'], // Alineación a la derecha
                        'buttonOptions' => ['class' => 'btn btn-sm btn-outline-secondary mr-2'],
                    ],
                ],
            ]); ?>
        </div>
        <?php Pjax::end(); ?>
    </div>
</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl {
            max-width: 3840px;
        }
    }
    .container {
        padding-right: 0;
    }
    .table-search {
        border: none;
        border-radius: 8px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        padding: 8px 12px;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .mantenimientos-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .btn-reset-search {
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal;
        text-overflow: ellipsis;
        overflow: hidden;
        word-wrap: break-word;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
    div.mantenimientos-index input.table-search {
        width: 50px;
    }
    .table td {
        max-width: 280px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: normal;
    }
    .text-right {
        text-align: right !important;
    }

    .estado-completado {
        background-color: rgba(0, 255, 0, 0.1) !important; /* Verde claro */
    }
    .estado-completado:hover {
        background-color: rgba(0, 255, 0, 0.2) !important; /* Verde más oscuro al pasar el mouse */
    }
    .estado-pendiente {
        background-color: rgba(255, 0, 0, 0.1) !important; /* Rojo claro */
    }
    .estado-pendiente:hover {
        background-color: rgba(255, 0, 0, 0.2) !important; /* Rojo más oscuro al pasar el mouse */
    }
</style>

<?php
$this->registerJs("
    document.getElementById('mantenimientos-search').addEventListener('keyup', function() {
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById('mantenimientos-search');
        filter = input.value.toUpperCase();
        table = document.getElementById('mantenimientos-table');
        tr = table.getElementsByTagName('tr');
        for (i = 1; i < tr.length; i++) {
            tr[i].style.display = 'none';
            td = tr[i].getElementsByTagName('td');
            for (j = 0; j < td.length; j++) {
                if (td[j]) {
                    txtValue = td[j].textContent || td[j].innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = '';
                        break;
                    }
                }
            }
        }
    });
    document.getElementById('reset-search').addEventListener('click', function() {
        document.getElementById('mantenimientos-search').value = '';
        var table = document.getElementById('mantenimientos-table');
        var tr = table.getElementsByTagName('tr');
        for (var i = 1; i < tr.length; i++) {
            tr[i].style.display = '';
        }
    });

    // Cambiar color de la fila al hacer clic en la casilla de verificación
    $('.estado-checkbox').on('change', function() {
        var isChecked = $(this).is(':checked');
        var row = $(this).closest('tr');
        if (isChecked) {
            row.removeClass('estado-pendiente').addClass('estado-completado');
        } else {
            row.removeClass('estado-completado').addClass('estado-pendiente');
        }

        // Actualizar el estado en la base de datos mediante una llamada AJAX
        var id = $(this).data('id');
        $.ajax({
            url: '" . Url::to(['mantenimientos/update-estado']) . "',
            type: 'POST',
            data: {
                id: id,
                estado: isChecked ? 1 : 0,
                _csrf: yii.getCsrfToken()
            },
            success: function(response) {
                if (response.success) {
                    console.log('Estado actualizado correctamente.');
                } else {
                    console.error('Error al actualizar el estado.');
                }
            },
            error: function(xhr, status, error) {
                console.error('Error al actualizar el estado:', error);
            }
        });
    });
");
?>

views/mantenimientos/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var app\models\Productos[] $productos */

$this->title = 'Actualizar Mantenimiento: ' . $model->id;

?>
<div class="mantenimientos-update container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .mantenimientos-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .mantenimientos-update {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
</style>

views/mantenimientos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */

$this->title = 'Mantenimiento ID: ' . $model->id;
\yii\web\YiiAsset::register($this);
?>

<div class="mantenimientos-view container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <div class="card shadow-sm p-4">
        <div class="d-flex justify-content-end mb-3">
            <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary mr-2']) ?>
            <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => '¿Estás seguro de que deseas eliminar este elemento?',
                    'method' => 'post',
                ],
            ]) ?>
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                [
                    'attribute' => 'idMaquinas0.nombre', // Accede al nombre de la máquina a través de la relación
                    'label' => 'Máquina', // Puedes personalizar la etiqueta si lo deseas
                ],
                [
                    'attribute' => 'idMaquinas0.numero_de_serie', // Accede al nombre de la máquina a través de la relación
                    'label' => 'Numero de serie', // Puedes personalizar la etiqueta si lo deseas
                ],
                [
                    'attribute' => 'descripcion',
                    'value' => function ($model) {
                        return !empty($model->descripcion) ? $model->descripcion : '-';
                    }
                ],
//                [
//                        'attribute' => 'estado',
//                        'format' => 'text',
//                        'value' => function ($model) {
//                            return $model->estado ? 'Pendiente' : 'Completado';
//                        },
//                        'label' => 'Estado'
//                    ],
                [
                    'attribute' => 'Fecha programada',
                    'value' => function($model) {
                        return Yii::$app->formatter->asDate($model->fecha);
                    },
                ],
            ],
        ]) ?>
    </div>

</div>

<style>
    
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .mantenimientos-view {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal; /* Permite el salto de línea */
        text-overflow: ellipsis; /* Agrega puntos suspensivos al texto que se desborda */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        word-wrap: break-word; /* Permite que las palabras largas se dividan y ajusten */
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .mantenimientos-view {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
    .table td {
        max-width: 1000px; /* Define un ancho máximo para las celdas */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        text-overflow: ellipsis; /* Agrega puntos suspensivos (...) al texto que se desborda */
        white-space: normal; /* Permite el salto de línea */
    }
</style>