models/Rutas.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "rutas".
 *
 * @property int $id
 * @property string $nombre
 * @property string|null $descripcion
 * @property string $duracion
 * @property float $distancia_km
 *
 * @property EmpresasRutas[] $empresasRutas
 * @property Empresas[] $idEmpresas
 */
class Rutas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $empresasIds; // Nueva propiedad virtual
    
    public static function tableName()
    {
        return 'rutas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['descripcion'], 'string', 'max' => 255],
            [['duracion'], 'safe'],
            [['distancia_km'], 'number'],
            [['nombre'], 'string', 'max' => 60],
            [['empresasIds'], 'required'],
            [['nombre', 'empresasIds'], 'validateUniqueRoute'], // Add custom validation rule
        ];
    }

    /**
     * Custom validation method to prevent duplicate route names for the same companies.
     */
    public function validateUniqueRoute($attribute, $params, $validator)
    {
        $query = self::find()->where(['nombre' => $this->nombre]);

        if (!$this->isNewRecord) {
            $query->andWhere(['not', ['id' => $this->id]]);
        }

        $existingRoutes = $query->all();

        foreach ($existingRoutes as $route) {
            $existingEmpresasIds = ArrayHelper::getColumn($route->getIdEmpresas()->asArray()->all(), 'id');
            sort($existingEmpresasIds);
            sort($this->empresasIds);

            if ($existingEmpresasIds === $this->empresasIds) {
                $this->addError($attribute, 'Ya existe una ruta con el mismo nombre para las mismas empresas.');
                break;
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre de la Ruta',
            'descripcion' => 'Descripción',
            'duracion' => 'Duracion',
            'distancia_km' => 'Distancia Km',
            'empresasIds' => 'Empresas',
        ];
    }

    /**
     * Gets query for [[EmpresasRutas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEmpresasRutas()
    {
        return $this->hasMany(EmpresasRutas::class, ['idRutas' => 'id']);
    }

    /**
     * Gets query for [[IdEmpresas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdEmpresas()
    {
        return $this->hasMany(Empresas::class, ['id' => 'idEmpresas'])->viaTable('empresas_rutas', ['idRutas' => 'id']);
    }
    
    public function getEmpresasList1()
    {
        $empresas = $this->idEmpresas;
        $empresasNames = [];

        foreach ($empresas as $empresa) {
            $empresasNames[] = $empresa->nombre;
        }

        return implode(', ', $empresasNames);
    }

    public function getEmpresasList()
    {
        return ArrayHelper::getColumn($this->getIdEmpresas()->asArray()->all(), 'id');
    }

    /**
     * Sobreescribe afterFind para cargar los IDs de las empresas asociadas a la ruta.
     */
    public function afterFind()
    {
        parent::afterFind();
        $this->empresasIds = $this->getEmpresasList();
    }

    /**
     * Sobreescribe beforeSave para manejar la relación con las empresas.
     *
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            // Aquí puedes manejar la lógica para guardar las relaciones con las empresas
            return true;
        }
        return false;
    }

    /**
     * Sobreescribe afterSave para manejar la relación con las empresas.
     *
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $this->saveEmpresas();
    }

    /**
     * Guarda las relaciones con las empresas.
     */
    protected function saveEmpresas()
    {
        EmpresasRutas::deleteAll(['idRutas' => $this->id]);
        if (is_array($this->empresasIds)) {
            foreach ($this->empresasIds as $empresaId) {
                $empresasRutas = new EmpresasRutas();
                $empresasRutas->idRutas = $this->id;
                $empresasRutas->idEmpresas = $empresaId;
                $empresasRutas->save();
            }
        }
    }
}

controllers/RutasController.php
<?php

namespace app\controllers;

use app\models\Rutas;
use app\models\search\RutasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

/**
 * RutasController implements the CRUD actions for Rutas model.
 */
class RutasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function actionMapa($id)
    {
        $ruta = $this->findModel($id);
        $empresas = $ruta->idEmpresas; // Empresas asociadas a la ruta
        return $this->render('mapa', [
            'ruta' => $ruta,
            'empresas' => $empresas,
        ]);
    }
    
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Rutas models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new RutasSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rutas model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Rutas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
{
    $model = new Rutas();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->id]);
    }

    return $this->render('create', [
        'model' => $model,
    ]);
}

public function actionUpdate($id)
{
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->id]);
    }

    return $this->render('update', [
        'model' => $model,
    ]);
}

    /**
     * Deletes an existing Rutas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rutas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Rutas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rutas::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/rutas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Empresas; // Asegúrate de importar el modelo Empresas

/** @var yii\web\View $this */
/** @var app\models\Rutas $model */
/** @var yii\widgets\ActiveForm $form */
/** @var app\models\Productos[] $productos */

$empresas = Empresas::find()->all();
$empresasList = ArrayHelper::map($empresas, 'id', 'nombre'); // Cambia 'nombre' al atributo adecuado de tu modelo

?>

<div class="rutas-form card shadow-sm p-4">

    <?php $form = ActiveForm::begin(['options' => ['class' => 'form-horizontal']]); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'nombre')->label('Nombre de la Ruta*')->textInput(['maxlength' => true, 'placeholder' => 'Ej: Ruta 1']) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'descripcion')->label('Descripción*')->textarea(['maxlength' => true, 'rows' => 1, 'placeholder' => 'Ej: Ruta de Santander a Torrelavega']) ?>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'empresasIds')->listBox($empresasList, [
                'multiple' => true,
                'size' => 12, // Ajusta el tamaño según tus necesidades
                'class' => 'form-control',
            ])->label('Empresas Participantes*') ?>
        </div>
    </div>

    <div class="form-group text-right">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const listBox = document.querySelector('.rutas-form .form-control[multiple]');
        listBox.addEventListener('click', function(e) {
            if (e.target.tagName === 'OPTION') {
                e.target.selected = !e.target.selected;
            }
        });

        // Evitar la selección múltiple predeterminada con arrastre
        listBox.addEventListener('mousedown', function(e) {
            e.preventDefault();
        });
    });
</script>

<style>
    .rutas-form .form-group {
        margin-bottom: 1rem;
    }
    .rutas-form .form-control {
        border-radius: 0.25rem;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .help-block {
        color: red;
        padding-left: 3px;
    }
    /* Alineación del botón */
    .rutas-form .text-right .btn {
        margin-top: 10px; /* Espacio superior */
    }
    /* Estilo para el listBox */
    .rutas-form .form-control[multiple] {
        height: auto;
        min-height: 200px;
        border-radius: 0.25rem;
    }
</style>

views/rutas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\search\RutasSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="rutas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'descripcion') ?>

    <?= $form->field($model, 'duracion') ?>

    <?= $form->field($model, 'distancia_km') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rutas/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var app\models\Productos[] $productos */

$this->title = 'Nueva Ruta';

?>
<div class="rutas-create container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .rutas-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .rutas-create {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
</style>

views/rutas/index.php
<?php

use app\models\Rutas;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

/** @var yii\web\View $this */
/** @var app\models\search\RutasSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Rutas';
?>
<div class="rutas-index container">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Nueva Ruta', ['create'], ['class' => 'btn btn-primary']) ?>
    </div>
    <div class="input-group mb-3" style="width: 450px;">
        <input type="text" id="rutas-search" class="form-control table-search" placeholder="Buscar...">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary btn-reset-search" type="button" id="reset-search">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <div class="card shadow-sm p-4">
        <?php Pjax::begin(); ?>
        <div class="card-body p-0">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => ['class' => 'table table-hover mb-0', 'id' => 'rutas-table'],
                'columns' => [
                    'nombre',
                    [
                        'attribute' => 'descripcion',
                        'format' => 'ntext',
                        'value' => function ($model) {
                            return !empty($model->descripcion) ? $model->descripcion : '-';
                        }
                    ],
                    [
                        'attribute' => 'Empresas',
                        'format' => 'html',
                        'value' => function ($model) {
                            $empresas = explode(', ', $model->getEmpresasList1());
                            if (!empty($empresas[0])) {
                                $html = '';
                                foreach ($empresas as $empresa) {
                                    $html .= Html::encode($empresa) . '<br>';
                                }
                                return $html;
                            }
                            return '-';
                        },
                        'label' => 'Empresas'
                    ],
                    [
                        'class' => ActionColumn::className(),
                        'urlCreator' => function ($action, Rutas $model, $key, $index, $column) {
                            return Url::toRoute([$action, 'id' => $model->id]);
                        },
                        
                        'buttonOptions' => ['class' => 'btn btn-sm btn-outline-secondary mr-2'],
                                'contentOptions' => ['class' => 'text-right'], // Alineación a la derecha
                        'template' => '{view} {update} {delete} <div>{mapa}</div>',
                        'buttons' => [
                            
                            'mapa' => function ($url, $model, $key) {
                                return Html::a('<i class="fa-solid fa-map-location-dot"></i>', Url::to(['rutas/mapa', 'id' => $model->id]), [
                                    'class' => 'btn btn-outline-secondary mt-2',
                                    'title' => 'Mapa',
                                    'data-pjax' => '0',
                                    'style' => 'width: 120px;margin-right: 8px;',
                                ]);
                            },

                        
                        ],
                    ],
                ],
            ]); ?>
        </div>
        <?php Pjax::end(); ?>
    </div>
</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl {
            max-width: 2560px;
        }
    }
    .container {
        padding-right: 0;
    }
    .table-search {
        border: none;
        border-radius: 8px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        padding: 8px 12px;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .rutas-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .btn-reset-search {
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal; /* Permite el salto de línea */
        text-overflow: ellipsis; /* Agrega puntos suspensivos al texto que se desborda */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        word-wrap: break-word; /* Permite que las palabras largas se dividan y ajusten */
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
    div.rutas-index input.table-search {
        width: 50px;
    }
    .table td {
        max-width: 250px; /* Define un ancho máximo para las celdas */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        text-overflow: ellipsis; /* Agrega puntos suspensivos (...) al texto que se desborda */
        white-space: normal; /* Permite el salto de línea */
    }
    
    
</style>

<?php
$this->registerJs("
    document.getElementById('rutas-search').addEventListener('keyup', function() {
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById('rutas-search');
        filter = input.value.toUpperCase();
        table = document.getElementById('rutas-table');
        tr = table.getElementsByTagName('tr');
        for (i = 1; i < tr.length; i++) {
            tr[i].style.display = 'none';
            td = tr[i].getElementsByTagName('td');
            for (j = 0; j < td.length; j++) {
                if (td[j]) {
                    txtValue = td[j].textContent || td[j].innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = '';
                        break;
                    }
                }
            }
        }
    });
    // Función para resetear el input de búsqueda y los resultados
    document.getElementById('reset-search').addEventListener('click', function() {
        document.getElementById('rutas-search').value = '';
        var table = document.getElementById('rutas-table');
        var tr = table.getElementsByTagName('tr');
        for (var i = 1; i < tr.length; i++) {
            tr[i].style.display = '';
        }
    });
");
?>

<?php
$this->registerJs("
    // Activar tooltips solo en las celdas con contenido truncado
    $('#rutas-table td').each(function() {
        if (this.offsetWidth < this.scrollWidth) {
            $(this).attr('title', $(this).text());
            $(this).tooltip();
        }
    });
");
?>

views/rutas/mapa.php
<?php
use yii\helpers\Html;
use yii\helpers\Json;

/* @var $this yii\web\View */
/* @var $ruta app\models\Rutas */
/* @var $empresas app\models\Empresa[] */

$this->title = 'Mapa de Ruta: ' . $ruta->nombre;

$empresasJson = Json::encode($empresas);
?>

<div class="d-flex justify-content-between align-items-center mb-3">
    <div>
        <h1 class="break-word"><?= Html::encode($this->title) ?></h1>
        <!--<p class="break-word"><?= Html::encode($ruta->descripcion) ?></p>-->
    </div>
    <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
</div>

<div id="map" class="map-container"></div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 20px;
        padding-left: 20px;
    }
    .table-search {
        border: none;
        border-radius: 8px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        padding: 8px 12px;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .map-container {
        height: 60vh;
        width: 100%;
        border: 1px solid #dee2e6;
        border-radius: 8px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal;
        text-overflow: ellipsis;
        overflow: hidden;
        word-wrap: break-word;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }

    /* Ocultar controles de enrutamiento de Leaflet Routing Machine */
    .leaflet-routing-container,
    .leaflet-bar.leaflet-routing-container,
    .leaflet-control.leaflet-routing-container {
        display: none !important;
    }

    /* Estilo para las etiquetas personalizadas */
    .label {
        color: blue;
        font-weight: bold;
        text-align: center;
        font-size: 12px;
    }

    /* Estilo para permitir corte de palabras y ajuste en múltiples líneas */
    .break-word {
        overflow-wrap: break-word;
        word-break: break-all;
        white-space: normal;
    }

    /* Hacer que el mapa se ajuste automáticamente tanto al ancho como al largo */
    #map {
        width: 100%;
        height: calc(100vh - 200px); /* Ajusta la altura relativa a la altura de la ventana, restando un espacio para otros elementos */
        max-height: 1000px; /* Altura máxima */
    }

    body {
        overflow: hidden; /* Evita el scroll vertical */
    }
</style>

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine/dist/leaflet-routing-machine.js"></script>
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
</head>
<body>
    <div id="map"></div>
    <div id="empresa-info" style="margin-top: 20px; font-size: 18px;"></div>

    <script>
    document.addEventListener("DOMContentLoaded", function() {
        var empresas = <?= $empresasJson ?>;
        var map = L.map('map').setView([0, 0], 2);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        var markers = [];
        var bounds = L.latLngBounds();

        empresas.forEach(function(empresa) {
            var coords = empresa.coordenadas.split(',');
            var latLng = L.latLng(parseFloat(coords[0]), parseFloat(coords[1]));
            var marker = L.marker(latLng).addTo(map);
            var label = L.divIcon({
                className: 'label',
                html: "<b>" + empresa.nombre + "</b>",
                iconSize: [100, 40],
                iconAnchor: [50, -20]  // Ajusta la posición de la etiqueta
            });

            L.marker(latLng, { icon: label }).addTo(map);

            markers.push(marker);
            bounds.extend(latLng);
        });

        map.fitBounds(bounds);

        // Configuración de la ruta
        var waypoints = markers.map(function(marker) {
            return marker.getLatLng();
        });

        L.Routing.control({
            waypoints: waypoints,
            routeWhileDragging: true,
            geocoder: L.Control.Geocoder.nominatim(),
            router: L.Routing.osrmv1({
                language: 'es',
                profile: 'driving-car'
            }),
            createMarker: function(i, waypoint) {
                return L.marker(waypoint.latLng);
            }
        }).addTo(map);
    });
    </script>
</body>
</html>

views/rutas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Rutas $model */

$this->title = 'Ruta ID: ' . $model->id;
\yii\web\YiiAsset::register($this);
?>

<div class="rutas-view container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <div class="card shadow-sm p-4">
        <div class="d-flex justify-content-end mb-3">
            <?= Html::a('Mapa', ['rutas/mapa', 'id' => $model->id], [
                'class' => 'btn btn-outline-secondary mr-2',
                'title' => 'Mapa',
                'data-pjax' => '0',
            ]) ?>
            <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary mr-2']) ?>
            <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => '¿Estás seguro de que deseas eliminar este elemento?',
                    'method' => 'post',
                ],
            ]) ?>
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'nombre',
                [
                    'attribute' => 'descripcion',
                    'format' => 'ntext',
                    'value' => function ($model) {
                        return !empty($model->descripcion) ? $model->descripcion : '-';
                    }
                ],
                [
                    'attribute' => 'Empresas',
                    'format' => 'html',
                    'value' => function ($model) {
                        $empresas = explode(', ', $model->getEmpresasList1());
                        if (!empty($empresas[0])) {
                            $html = '';
                            foreach ($empresas as $empresa) {
                                $html .= Html::encode($empresa) . '<br>';
                            }
                            return $html;
                        }
                        return '-';
                    },
                    'label' => 'Empresas'
                ],
                //'duracion',
                //'distancia_km',
            ],
        ]) ?>
    </div>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl {
            max-width: 2560px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .rutas-view {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal; /* Permite el salto de línea */
        text-overflow: ellipsis; /* Agrega puntos suspensivos al texto que se desborda */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        word-wrap: break-word; /* Permite que las palabras largas se dividan y ajusten */
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .rutas-view {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
    .table td {
        max-width: 1000px; /* Define un ancho máximo para las celdas */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        text-overflow: ellipsis; /* Agrega puntos suspensivos (...) al texto que se desborda */
        white-space: normal; /* Permite el salto de línea */
    }
</style>