models/Contratos.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "contratos".
 *
 * @property int $id
 * @property int $idEmpresas
 * @property int $idMaquinas
 * @property string $tipo
 * @property string|null $descripcion
 * @property string $fecha_de_inicio
 * @property string $fecha_fin
 *
 * @property Empresas $idEmpresas0
 * @property Maquinas $idMaquinas0
 */
class Contratos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contratos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idEmpresas'], 'required', 'message' => 'Debe de seleccionar una empresa.'],
            [['idMaquinas'], 'required', 'message' => 'Debe de seleccionar una maquina.'],
            [['fecha_fin'], 'required', 'message' => 'Debe de introducir una fecha fin'],
            [['fecha_de_inicio'], 'required', 'message' => 'Debe de introducir una fecha de inicio'],
            [['tipo'], 'required', 'message' => 'Debe de introducir el tipo de contrato.'],

            [['idEmpresas', 'idMaquinas'], 'integer'],
            [['descripcion'], 'string', 'max' => 255],
            [['fecha_de_inicio', 'fecha_fin'], 'safe'],
            [['tipo'], 'string', 'max' => 60],
            [['idEmpresas'], 'exist', 'skipOnError' => true, 'targetClass' => Empresas::class, 'targetAttribute' => ['idEmpresas' => 'id']],
            [['idMaquinas'], 'exist', 'skipOnError' => true, 'targetClass' => Maquinas::class, 'targetAttribute' => ['idMaquinas' => 'id']],
            [['fecha_de_inicio'], 'compare', 'compareAttribute' => 'fecha_fin', 'operator' => '<=', 'type' => 'date', 'message' => 'La fecha de inicio debe ser anterior o igual a la fecha de fin.', 
                'when' => function($model) {
                    return !empty($model->fecha_fin);
                },
                'whenClient' => "function (attribute, value) {
                    return $('#" . Html::getInputId($this, 'fecha_fin') . "').val() != '';
                }"
            ],
            [['fecha_fin'], 'compare', 'compareAttribute' => 'fecha_de_inicio', 'operator' => '>=', 'type' => 'date', 'message' => 'La fecha de fin debe ser posterior o igual a la fecha de inicio.'],
            ['idMaquinas', 'validateDates'],
        ];
    }

    /**
     * Custom validation method to prevent overlapping contracts for the same machine.
     */
    public function validateDates($attribute, $params, $validator)
    {
        $exists = self::find()
            ->where(['idMaquinas' => $this->idMaquinas])
            ->andWhere(['not', ['id' => $this->id]])
            ->andWhere(['<=', 'fecha_de_inicio', $this->fecha_fin])
            ->andWhere(['>=', 'fecha_fin', $this->fecha_de_inicio])
            ->exists();

        if ($exists) {
            $this->addError($attribute, 'Esta máquina ya tiene un contrato en las fechas seleccionadas.');
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idEmpresas' => 'Empresa',
            'idMaquinas' => 'Máquina',
            'tipo' => 'Tipo',
            'descripcion' => 'Descripción',
            'fecha_de_inicio' => 'Fecha de Inicio',
            'fecha_fin' => 'Fecha de Fin',
        ];
    }

    /**
     * Gets query for [[IdEmpresas0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdEmpresas0()
    {
        return $this->hasOne(Empresas::class, ['id' => 'idEmpresas']);
    }

    /**
     * Gets query for [[IdMaquinas0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdMaquinas0()
    {
        return $this->hasOne(Maquinas::class, ['id' => 'idMaquinas']);
    }
    
    public function getDuracion()
    {
        $inicio = new \DateTime($this->fecha_de_inicio);
        $fin = new \DateTime($this->fecha_fin);
        $intervalo = $inicio->diff($fin);

        // Formatear la duración
        $duracion = '';
        if ($intervalo->y > 0) {
            $duracion .= $intervalo->y . ' año/s';
        }
        if ($intervalo->m > 0) {
            $duracion .= ($duracion !== '' ? ', ' : '') . $intervalo->m . ' mes/es';
        }
        if ($intervalo->d > 0) {
            $duracion .= ($duracion !== '' ? ' y ' : '') . $intervalo->d . ' día/s';
        }

        return $duracion;
    }
}

controllers/ContratosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Contratos;
use app\models\search\ContratosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Mpdf\Mpdf;

/**
 * ContratosController implements the CRUD actions for Contratos model.
 */
class ContratosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Contratos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ContratosSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Contratos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Contratos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Contratos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->validate() && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Contratos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->validate() && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Contratos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Contratos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Contratos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionExportPdf($id)
    {
        $model = $this->findModel($id);

        // Renderizar la vista del contrato en una variable
        $content = $this->renderPartial('pdf', [
            'model' => $model,
        ]);

        // Configurar mpdf
        $mpdf = new Mpdf();
        $mpdf->WriteHTML($content);
        
        // Nombre del archivo PDF
        $pdfFileName = 'Contrato_' . $model->id . '.pdf';

        // Enviar el PDF al navegador para descarga
        return $mpdf->Output($pdfFileName, \Mpdf\Output\Destination::INLINE);
    }
    
    protected function findModel($id)
    {
        if (($model = Contratos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/contratos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var yii\widgets\ActiveForm $form */
/** @var app\models\Productos[] $productos */

?>

<div class="contratos-form card shadow-sm p-4">

    <?php $form = ActiveForm::begin(['options' => ['class' => 'form-horizontal']]); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'idMaquinas')->label('Máquina*')->dropDownList(
                ArrayHelper::map(\app\models\Maquinas::find()->all(), 'id', function($maquina) {
                    return $maquina->nombre . ' - ' . $maquina->numero_de_serie;
                }), 
                ['prompt' => 'Seleccione una Máquina']
            ) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'idEmpresas')->label('Empresa*')->dropDownList(
                \yii\helpers\ArrayHelper::map(\app\models\Empresas::find()->all(), 'id', 'nombre'),
                ['prompt' => 'Seleccione una Empresa']
            ) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'tipo')->label('Tipo de contrato*')->textInput(['maxlength' => true, 'placeholder' => 'Ej: Porcentaje']) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'descripcion')->textarea(['maxlength' => true, 'rows' => 1, 'placeholder' => 'Ej: Contrato de un 10% de las ventas']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'fecha_de_inicio')->label('Fecha de Inicio*')->input('date') ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'fecha_fin')->label('Fecha Fin*')->input('date') ?>
        </div>
    </div>

    <div class="form-group text-right">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<style>
    .contratos-form .form-group {
        margin-bottom: 1rem;
    }
    .contratos-form .form-control {
        border-radius: 0.25rem;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .help-block {
        color: red;
        padding-left: 3px;
    }
    /* Alineación del botón */
    .contratos-form .text-right .btn {
        margin-top: 10px; /* Espacio superior */
    }
</style>

views/contratos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\search\ContratosSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="contratos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'idEmpresas') ?>

    <?= $form->field($model, 'idMaquinas') ?>

    <?= $form->field($model, 'tipo') ?>

    <?= $form->field($model, 'descripcion') ?>

    <?php // echo $form->field($model, 'fecha_de_inicio') ?>

    <?php // echo $form->field($model, 'fecha_fin') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/contratos/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var app\models\Productos[] $productos */

$this->title = 'Nuevo Contratos';

?>
<div class="contratos-create container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .contratos-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .contratos-create {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
</style>

views/contratos/index.php
<?php

use app\models\Contratos;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

/** @var yii\web\View $this */
/** @var app\models\search\ComprasSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Contratos';

?>
<div class="contratos-index container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Nueva Contrato', ['create'], ['class' => 'btn btn-primary']) ?>
    </div>
    <div class="input-group mb-3" style="width: 450px;">
        <input type="text" id="contratos-search" class="form-control table-search" style="width: 50px;" placeholder="Buscar...">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary btn-reset-search" type="button" id="reset-search">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>

    <div class="card shadow-sm p-4">
        <?php Pjax::begin(); ?>
        <div class="card-body p-0">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => ['class' => 'table table-hover mb-0', 'id' => 'contratos-table'],
                'columns' => [
                    [
                        'attribute' => 'idMaquinas',
                        'value' => 'idMaquinas0.nombre',
                        'label' => 'Máquina'
                    ],
                    [
                        'attribute' => 'idMaquinas',
                        'value' => 'idMaquinas0.numero_de_serie',
                        'label' => 'Número de Serie'
                    ],
                    [
                        'attribute' => 'idEmpresas',
                        'value' => 'idEmpresas0.nombre',
                        'label' => 'Empresa'
                    ],
                    'tipo',
                    [
                        'attribute' => 'descripcion',
                        'format' => 'ntext',
                        'value' => function ($model) {
                            return !empty($model->descripcion) ? $model->descripcion : '-';
                        }
                    ],
                    [
                        'attribute' => 'fecha_de_inicio',
                        'format' => ['date', 'php:d-m-Y'],
                        'contentOptions' => ['style' => 'white-space: nowrap;'],
                    ],
                    [
                        'attribute' => 'fecha_fin',
                        'format' => ['date', 'php:d-m-Y'],
                        'contentOptions' => ['style' => 'white-space: nowrap;'],
                    ],
                    [
                        'class' => ActionColumn::className(),
                        'urlCreator' => function ($action, Contratos $model, $key, $index, $column) {
                            return Url::toRoute([$action, 'id' => $model->id]);
                        },
                        'buttonOptions' => ['class' => 'btn btn-sm btn-outline-secondary mr-2'],
                        'contentOptions' => ['class' => 'text-right'], // Alineación a la derecha
                        'template' => '{view} {update} {delete} <div>{export-pdf}</div>',
                        'buttons' => [
                            'export-pdf' => function ($url, $model, $key) {
                                return Html::a('<i class="fas fa-file-pdf"></i>', '#', [
                                    'class' => 'btn btn-outline-secondary mt-2', // Quitamos la clase btn-sm
                                    'title' => 'Exportar a PDF',
                                    'data-pjax' => '0',
                                    'style' => 'width: 120px;margin-right: 8px;',
                                    'onclick' => 'window.open("' . Url::to(['contratos/export-pdf', 'id' => $model->id]) . '", "_blank"); return false;',
                                ]);
                            },
                        ],
                    ],



                ],
            ]); ?>
        </div>
        <?php Pjax::end(); ?>
    </div>
</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl {
            max-width: 3840px;
        }
    }
    
    .container {
        padding-right: 0;
    }
    .table-search {
        border: none;
        border-radius: 8px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        padding: 8px 12px;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .contratos-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .btn-reset-search {
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal; /* Permite el salto de línea */
        text-overflow: ellipsis; /* Agrega puntos suspensivos al texto que se desborda */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        word-wrap: break-word; /* Permite que las palabras largas se dividan y ajusten */
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
    div.contratos-index input.table-search {
        width: 50px;
    }
    .table td {
        max-width: 200px; /* Define un ancho máximo para las celdas */
        overflow: hidden; /* Oculta el texto que se desborda de la celda */
        text-overflow: ellipsis; /* Agrega puntos suspensivos (...) al texto que se desborda */
        white-space: normal; /* Permite el salto de línea */
    }
</style>

<?php
$this->registerJs("
    document.getElementById('contratos-search').addEventListener('keyup', function() {
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById('contratos-search');
        filter = input.value.toUpperCase();
        table = document.getElementById('contratos-table');
        tr = table.getElementsByTagName('tr');
        for (i = 1; i < tr.length; i++) {
            tr[i].style.display = 'none';
            td = tr[i].getElementsByTagName('td');
            for (j = 0; j < td.length; j++) {
                if (td[j]) {
                    txtValue = td[j].textContent || td[j].innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = '';
                        break;
                    }
                }
            }
        }
    });
    // Función para resetear el input de búsqueda y los resultados
    document.getElementById('reset-search').addEventListener('click', function() {
        document.getElementById('contratos-search').value = '';
        var table = document.getElementById('contratos-table');
        var tr = table.getElementsByTagName('tr');
        for (var i = 1; i < tr.length; i++) {
            tr[i].style.display = '';
        }
    });
");
?>

<?php
$this->registerJs("
    // Activar tooltips solo en las celdas con contenido truncado
    $('#compras-table td').each(function() {
        if (this.offsetWidth < this.scrollWidth) {
            $(this).attr('title', $(this).text());
            $(this).tooltip();
        }
    });
");
?>

views/contratos/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */
/** @var app\models\Productos[] $productos */

$this->title = 'Actualizar Contrato: ' . $model->id;

?>
<div class="contratos-update container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .contratos-index {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .contratos-update {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
</style>

views/contratos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Compras $model */

$this->title = 'Contrato ID: ' . $model->id;
\yii\web\YiiAsset::register($this);
?>

<div class="contratos-view container">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mb-0"><?= Html::encode($this->title) ?></h1>
        <?= Html::a('Volver a la lista', ['index'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <div class="card shadow-sm p-4">
        <div class="d-flex justify-content-between mb-3">
            <div>
                <!-- Aquí estaba el botón de Exportar a PDF anteriormente -->
            </div>
            <div>
                <?= Html::a('Exportar a PDF', ['contratos/export-pdf', 'id' => $model->id], [
                    'class' => 'btn btn-outline-secondary mr-2',
                    'title' => 'Exportar a PDF',
                    'target' => '_blank',
                ]) ?>
                <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary mr-2']) ?>
                <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => '¿Estás seguro de que deseas eliminar este elemento?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                [
                    'attribute' => 'idMaquinas0.nombre',
                    'label' => 'Máquina',
                ],
                [
                    'attribute' => 'idMaquinas0.numero_de_serie',
                    'label' => 'Número de Serie',
                ],
                [
                    'attribute' => 'idEmpresas0.nombre',
                    'label' => 'Empresa',
                ],
                'tipo',
                [
                    'attribute' => 'descripcion',
                    'format' => 'ntext',
                    'value' => function ($model) {
                        return !empty($model->descripcion) ? $model->descripcion : '-';
                    }
                ],
                [
                    'attribute' => 'Fecha de inicio',
                    'value' => function($model) {
                        return Yii::$app->formatter->asDate($model->fecha_de_inicio);
                    },
                ],
                [
                    'attribute' => 'Fecha fin',
                    'value' => function($model) {
                        return Yii::$app->formatter->asDate($model->fecha_fin);
                    },
                ],
            ],
        ]) ?>
    </div>

</div>

<style>
    @media (min-width: 1200px) {
        .container, .container-sm, .container-md, .container-lg, .container-xl, .compras-create container, .compras-form card shadow-sm p-4 {
            max-width: 2540px;
        }
    }
    .container {
        padding-right: 0;
    }
    .content {
        background-color: #f8f9fa;
    }
    .summary {
        padding: 6px;
    }
    .contratos-view {
        background-color: #f8f9fa;
        padding: 20px;
    }
    .card {
        border: none;
        border-radius: 8px;
    }
    .card .table thead th {
        background-color: #f1f1f1;
        border-bottom: 2px solid #dee2e6;
    }
    .card .table tbody tr:hover {
        background-color: #e9ecef;
    }
    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .btn-primary:hover {
        background-color: #004494;
        border-color: #004494;
    }
    .table td, .table th {
        white-space: normal;
        text-overflow: ellipsis;
        overflow: hidden;
        word-wrap: break-word;
        overflow-wrap: break-word;
    }
    .grid-view .action-column .btn {
        margin-right: 2px;
    }
    .contratos-view {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }
    .btn-outline-secondary:hover {
        background-color: #6c757d;
        color: #fff;
    }
    .table td {
        max-width: 1000px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: normal;
    }
</style>